### PR TITLE
WIP: inline spread syntax

### LINKED ISSUE #221: Inline spread syntax where possible
**Bug report or Feature request?**
Feature request

**Version (complete output of `terser -V`)**
terser 3.14.0

**Complete CLI command or `minify()` options used**
`terser --compress --module input.js`

**`terser` input**

```js
const ENABLED_FEATURE = true;
const DISABLED_FEATURE = false;

// Spread in function calls
f(
	...[1],
	...ENABLED_FEATURE ? [2] : [],
	...DISABLED_FEATURE ? [3] : [],
);

// Spread in array literals
f([
	...[1],
	...ENABLED_FEATURE ? [2] : [],
	...DISABLED_FEATURE ? [3] : [],
]);

// Spread in object literals
f({
	...{ a: 1 },
	...ENABLED_FEATURE && { b: 2 },
	...DISABLED_FEATURE && { c: 3 },
});
```

**`terser` output or error** [line breaks added for clarity]
```js
f(...[1],...[2],...[]),
f([...[1],...[2],...[]]),
f({...{a:1},...{b:2},...!1});
```

**Expected result**
```js
f(1,2),
f([1,2]),
f({a:1,b:2});
```

----

The enabled/disabled feature case is realistic; we have several such compile-time flags in FastMail: for FastMail-specific (rather than generic) stuff, for local testing, and for differences between our desktop and mobile interfaces. Our build system is old and currently uses what amounts to #ifdef, but we’re in the process of updating it, and I’d love to be able to use spread syntax to handle it with no minified code size penalty.

Spread in object literals is the most interesting of the three contexts, but I believe it is reasonable to always inline spread syntax if the value being spread comes down to simple literals as shown above; `{a:1,...{a:2},...x,...{a:3},...y}` is correctly equivalent to `{a:1,a:2,...x,a:3,...y}`.

### PR DESCRIPTION
**Pull request by chris-morgan**
I’m not confident about where things “should” be placed in compress.js, but other than that I think this is complete.

Fixes #221.

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
Nice PR! I suppose this optimisation won't be run many times, but it's nice to have it.

**Comment by fabiosantoscode** [comment]
However in the future we're going to start using prepack, which already does this optimisation. Have a look at the project.

**Comment by chris-morgan** [comment]
Ooh, prepack looks nice indeed. Whenever I’m writing JavaScript instead of Rust, I miss having an optimiser that can do lots of advanced stuff like this.

As I mentioned in #221 where I requested this feature yesterday, I’m updating FastMail’s codebase build tooling, and this optimisation is *very* desirable for us—it’s not a *huge* deal in the scheme of things, but we do care about our code size and such things, and spread definitely gets a bit bigger when converted back to ES5, and this optimisation makes switching such ifdefs in object literals zero-cost.

I love zero-cost abstractions.

Thanks for accepting this. Any projected timeline to share for a stable Prepack-based Terser?

**Comment by fabiosantoscode** [comment]
There's currently no timeline for this. It shouldn't take more than a month. If it does please you in the end, consider supporting the project on patreon ;)

**Pull request merged**
