### PR TITLE
Use Set for mangling

### PR DESCRIPTION
**Pull request by MattiasBuelens**
The name and property manglers keep track of which names are already in use using a string array. However, when you have a large number of variables or properties, looking up a name in this array can become slow.

This changes the manglers to use a ES2015 `Set` instead.

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
Note: this will probably conflict with #271. I can rebase this PR if the other PR lands first. 😉

**Comment by fabiosantoscode** [comment]
Great stuff, it's always good to have a speedup :)

> Note: this will probably conflict with #271

Yeah. I've merged it first because it came first. Sorry!

But there's something I have to ask you before I merge: Can you make this use an ES6 `Set` instead of a Dictionary? It's going to be a lot faster!

The Dictionary class is on its way out. Creating an issue for it

**Comment by MattiasBuelens** [comment]
> But there's something I have to ask you before I merge: Can you make this use an ES6 `Set` instead of a Dictionary? It's going to be a lot faster!

Yes, I wanted to do that, but I wasn't sure if I could use `Set` already. Good to know that we can.

I'll rework it tomorrow or something.

**Comment by fabiosantoscode** [comment]
Thanks!

**Comment by MattiasBuelens** [comment]
As suggested, I changed the `Dictionary` usages to `Set` instead. I've added the `es6` environment to the ESLint config, so we can use ES2015 globals anywhere in the code. 🙂

**Comment by fabiosantoscode** [comment]
Great stuff! Thanks a lot for your help, it's really appreciated as I don't have the time to deal with most terser issues.

**Pull request merged**
