### PR TITLE
fix: add missed type defines

### PR DESCRIPTION
**Pull request by int64ago**
ref: https://github.com/terser-js/terser#compress-options

### CODE REVIEW

**Comment by int64ago** [comment]
Please publish a patch version, thanks.

**Comment by RebeccaStevens** [comment]
Would you like to also fix the issues in #290 in this PR?

**Comment by fabiosantoscode** [comment]
Hy there, thanks for the PR!

I considered releasing a patch version for a bit, and then I thought of the consequences of that action. This project is hard to maintain as it is so I don't want to create a precedent of backporting things to a previous version.

So now I plan to stop supporting 3.x as soon as 4.0 is released. I might consider backporting fixes to serious bugs with no workaround, only because 4.0 drops node 4 (as the name correctly implies), but this is not serious and I think as a workaround you can force typescript to let you do what you want to do with a specific function.

**Comment by fabiosantoscode** [comment]
Thanks for this. Terser 4 has been delayed and is now in a separate branch, so this can go in.

**Pull request merged**
