### PR TITLE
drop empty object destructure decl when `pure_getters` true

### PR DESCRIPTION
**Pull request by kzc**

### CODE REVIEW

**Comment by kzc** [comment]
Odd... CI tests are not running. Does something have to be set after moving to terser-js?

**Comment by kzc** [comment]
Might have to contact GitHub to resolve. 
See https://github.com/travis-ci/travis-ci/issues/7643

**Comment by kzc** [comment]
@fabiosantoscode I think I see what's going on... as far as Travis CI is concerned `terser-js/terser` is a new account since the org name changed. Have to sign up to enable it: https://docs.travis-ci.com/user/getting-started/

**Comment by fabiosantoscode** [comment]
terser-js is now activated on travis!

**Comment by fabiosantoscode** [comment]
Let's merge this and have a release

**Pull request merged**
