### PR TITLE
Add test for collapse_vars with esm

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/terser-js/terser/issues/333

### CODE REVIEW

**Comment by TrySound** [comment]
@fabiosantoscode Could you guide me where to start?
if I replace `export function baseRest` with `window.baseRest = baseRest` all works as expected. Maybe export is marked somehow incorrectly?

**Comment by fabiosantoscode** [comment]
Hey there! Good test :)

Let me have a quick look at lib/compress and I'll let you know.

**Comment by fabiosantoscode** [comment]
I meant to take only a quick look, but this took me a lot longer than I expected...

The function that handles the `collapse_vars` option is called `collapse`

I'm guessing the issue is in the `extract_candidates` function. It doesn't take AST_Export into account.

**Comment by TrySound** [comment]
Should it add AST_Export to candidates or only traverse it? Traverse will get AST_Defun which is not processed by extract_candidates too. Adding to canditates didn't change anything too.

```js
                } else if (expr instanceof ast_vardef) {
                    if (expr.value) {
                        candidates.push(hit_stack.slice());
                        extract_candidates(expr.value);
                    }
                } else if (expr instanceof ast_export) {
                    if (expr.exported_definition) {
                        candidates.push(hit_stack.slice());
                        extract_candidates(expr.exported_definition)
                    }
                }
                hit_stack.pop();
            }

````

**Comment by TrySound** [comment]
Looks like candidates is not responsible for that. I do not have an idea how to fix this.

**Pull request closed without merging**
