### PR TITLE
test node 11

### PR DESCRIPTION
**Pull request by fabiosantoscode**
Drop node 10 for node 11, since bugs will probably occur on both.

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
What do you think @kzc

**Comment by kzc** [comment]
> Drop node 10 for node 11, since bugs will probably occur on both.

That's not necessarily true. Bugs can exist in any version.

We should only test stable released (even numbered) node versions.

Add Node 11 if you like, but keep 10.

**Comment by fabiosantoscode** [comment]
Got it

**Comment by Martii** [comment]
Yah it's a bit confusing that 10 isn't mentioned now... there's some bugs in 11 that will prevent us from going to it immediately. Thanks for keeping 10 as a test path here. :)

**Pull request merged**
