### PR TITLE
have `reduce_vars` and  `inline` respect `top_retain`

### LINKED ISSUE #161: Unexpected top_retain/reduce_vars/unused results
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V`)**

3.10.11

**Complete CLI command or `minify()` options used**

See [the failing test commit](https://github.com/terser-js/terser/commit/cb23672efe62df0615eac60b01926b9b322c0522).

When the `top_retain` function is called twice the output is fine but when it is only called once then the output is not what one would expect.

### PR DESCRIPTION
**Pull request by kzc**
fixes #161

### CODE REVIEW

**Comment by kzc** [comment]
Just noticed that `reduce_vars` doesn't respect `top_retain` for regular (non function) variables...
```
$ echo 'var x=1, y=2; console.log(x, y, x+y);' | terser -c top_retain=y
var y=2;console.log(1,2,3);
```
PR hasn't addressed that yet.

**Comment by kzc** [comment]
This PR is good to merge. 

Also added source map support to `test/run-tests.js` because errors in ill-formed tests were otherwise completely undecipherable.

**Comment by opichals** [comment]
@kzc Thank you! Verified [my tests](https://github.com/terser-js/terser/commit/cb23672efe62df0615eac60b01926b9b322c0522) are passing with the current version of this PR.

**Comment by kzc** [comment]
@fabiosantoscode Feel free to merge.

Between this PR and #166 it's probably worthy of a release.

**Comment by fabiosantoscode** [comment]
Published 3.10.12

**Pull request merged**
