### PR TITLE
Don't inline default assign if arg is non-primitive

### LINKED ISSUE #407: function/object inlining breaks loose equality checks on default parameters that are inlined
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V` or specific git commit)**

`4.1.2`

**Complete CLI command or `minify()` options used**

```bash
terser --parse=acorn entry.js -c toplevel
```

**`terser` input**

```js
const defaultArg = input => input;

const fn = (arg = defaultArg) => arg

if(fn() !== fn()) throw new Error('Something is broken');
```

**`terser` output or error**

```js
const fn=(arg=(input=>input))=>arg;if(fn()!=fn())throw new Error("Something is broken");
```

Beautified for readability

```js
const fn = (arg = (input => input)) => arg;

if (fn() != fn()) throw new Error("Something is broken");
```

**Expected result**

The default param if it isn't a primitive (is an object/function) shouldn't be inlined.  E.g.

```js
const defaultArg = input => input;
const fn = (arg = defaultArg) => arg;

if (fn() != fn()) throw new Error("Something is broken");
```

If you run the input code it exits cleanly, if you run the code terser outputs it throws an error.  The code is correct but the over-eager inlining of the top level function causes issues.

### PR DESCRIPTION
**Pull request by L2jLiga**
Fixes #407

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
OMG I literally just finished fixing this bug, was just in the process of writing the tests!

I will add your changes if they don't seem like a performance issue, since my code doesn't linline `const iWillBeDefault = 'primitive'` into default parameters.

Also I'll steal your tests :D

**Comment by fabiosantoscode** [comment]
Protip: If the `expect` clause is just the same as the input, just don't specify it. You can trust `expect_stdout` to be used to test instead.

**Comment by fabiosantoscode** [comment]
Don't add commits, I've already fixed this when I imported your tests. I have to check out how I can add an author to a git commit because we technically did this together.

**Comment by L2jLiga** [comment]
> I literally just finished fixing this bug, was just in the process of writing the tests!

Hah, we're thinking alike 😄 

> Protip: If the `expect` clause is just the same as the input, just don't specify it. You can trust `expect_stdout` to be used to test instead.

> Don't add commits

Sure

**Comment by L2jLiga** [comment]
Hmm, default_assign_primitive test failed.. Which option I forget to enable? 🤔 🙄

**Comment by fabiosantoscode** [comment]
I'll figure that one out.

**Comment by fabiosantoscode** [comment]
This is a lot bigger than just looking at whether the parent is a default assignment :/ it could be a grandparent. Also, there's lots more cases than it seems. I want to send a PR for this, can you have a look when it's done?

**Comment by L2jLiga** [comment]
Sure

**Comment by L2jLiga** [comment]
Hey @fabiosantoscode, how is your progress on that?

**Comment by fabiosantoscode** [comment]
@L2jLiga I struggled a lot, then threw everything away and started over. I released 4.2.0 without this fix because there were other things in the pipeline which I wanted to release.

**Comment by fabiosantoscode** [comment]
@L2jLiga it's beginning to look like `reduce_funcs` has to go away entirely to fix this.

**Comment by L2jLiga** [comment]
Then I suggest to disable it by default

**Comment by L2jLiga** [comment]
Also it would be nice to have several fixes available, then we can choose one of them and improve by using other fixes

**Comment by fabiosantoscode** [comment]
I can't leave reduce_funcs in without turning it into `unsafe_reduce_funcs` first. Anything that doesn't have `unsafe` in it is guaranteed to not screw up the code.

**Comment by fabiosantoscode** [comment]
Also, it looks like weird things happen when `reduce_funcs` is turned off so I'm going to handle that first :/

**Comment by fabiosantoscode** [comment]
Fixed in another PR

**Pull request closed without merging**
