### PR TITLE
Split utils to separate files

### PR DESCRIPTION
**Pull request by L2jLiga**
It gets rid of one of circular dependency warnings during build.

Based on #376

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
I wonder how we can fix this dependency loop without splitting utils into almost one file per function...

Surely there's a way to resolve this without such a massive change!

**Comment by L2jLiga** [comment]
PR updated

Now I moved only `first_in_statement` outside of `utils`

**Comment by fabiosantoscode** [comment]
Cool, `first_in_statement` was a bother. Could you fix the conflicts? Also, let's try and have full file extensions everywhere. `lib/utils/index.js` instead of `lib/utils/index`. This will make it easier to use Deno when the day comes, and is also the standard now.

**Comment by L2jLiga** [comment]
Conflicts fixed, file extensions added to imports 😌

**Comment by fabiosantoscode** [comment]
This is awkward... I caused conflicts by merging your other PR

**Comment by L2jLiga** [comment]
Hmm.. conflicts.. I will fix them

**Comment by L2jLiga** [comment]
Fixed

**Comment by fabiosantoscode** [comment]
Great stuff :) thanks!

**Pull request merged**
