### PR TITLE
Allow for custom funcs on Object.prototype

### PR DESCRIPTION
**Pull request by BenBeattieHood**
Teeny tiny bugfix. Resolves https://github.com/terser-js/terser/issues/332 to allow for functions added to the Object prototype.

### CODE REVIEW

**Comment by BenBeattieHood** [comment]
@alexlamsl please would you take a look?

**Comment by alexlamsl** [comment]
I have nothing to do with this project.

**Comment by BenBeattieHood** [comment]
Sorry, the project lists you as a contributor as the log for this file shows you as the last author for this line. @fabiosantoscode can you review?

**Comment by fabiosantoscode** [comment]
Nice catch, and thank you. This goes right in.

**Pull request merged**
