### PR TITLE
more efficient fix for `inline: 3` loop bug

### PR DESCRIPTION
**Pull request by kzc**
improve the #152 fix for #120 

* up to 15% faster in some cases
* use shallow clone for value rather than deep clone
* no test regressions

### CODE REVIEW

**Comment by kzc** [comment]
Timings on a 5MB input:

terser 3.10.7:
```
$ /usr/bin/time terser app.js -mc passes=2 | shasum
       34.17 real        35.72 user         0.51 sys
5ea134c00650c771f5e690ee863002a2115c49a5  -
```
This PR:
```
$ /usr/bin/time terser app.js -mc passes=2 | shasum
       29.72 real        31.22 user         0.48 sys
5ea134c00650c771f5e690ee863002a2115c49a5  -
```

**Comment by kzc** [comment]
This PR coincidentally fixes a regression - see #156 for details.

**Comment by fabiosantoscode** [comment]
Cool.

**Comment by kzc** [comment]
@fabiosantoscode I think 623cc65daedda6fa9703bb4b0569148839a9e988 is worth releasing. It fixes a number of regressions seen in the wild.

The other bugs I discovered in the course of looking at #156 that will be addressed by PR #158 have existed in Terser since it was created and were not independently reported.

**Comment by kzc** [comment]
@fabiosantoscode Thanks. 

I don't see 3.10.9 on [master](https://github.com/terser-js/terser/commits/master). Perhaps forgot to push?

**Comment by kzc** [comment]
@fabiosantoscode Unfortunately 3.10.9 does not contain the bug fix in this PR and https://github.com/terser-js/terser/commit/623cc65daedda6fa9703bb4b0569148839a9e988.

```
$ npm install terser

$ node_modules/terser/bin/uglifyjs -V
terser 3.10.9

$ cat -n node_modules/terser/lib/compress.js | head -5036 | tail -1
  5036	                right: value.clone(true)

$ cat demo.js
(function (root, factory) {
  root.CryptoJS = factory()
})(this, function () {
  var CryptoJS = CryptoJS || function (Math) {
    var C = {};
    C.demo = function(n) {
      return Math.ceil(n);
    };
    return C;
  }(Math);
  return CryptoJS
});
var result = this.CryptoJS.demo(1.3);
console.log(result);

$ cat demo.js | node
2

$ cat demo.js | node_modules/terser/bin/uglifyjs -bc | node
[stdin]:5
            return Math.ceil(n);
                       ^
TypeError: Cannot read property 'ceil' of undefined
```

**Comment by fabiosantoscode** [comment]
Sorry, I've messed it up. It should be up now in 3.10.10

**Comment by kzc** [comment]
No sweat. Thanks!

**Comment by kzc** [comment]
@fabiosantoscode Unfortunately there's a problem. 

https://github.com/terser-js/terser/commits/master is showing 3.10.9 instead of 3.10.10. So the npm registry and master are now out of sync for the the last 2 releases.

Can you carefully repair master to have a 3.10.10 version in package.json  and then commit/tag/push that **without doing an npm publish**?

Then cutting a brand new 3.10.11 might be a good idea to get npm and the github repo in sync once again.

**Comment by kzc** [comment]
I see 3.10.10 is in place now. Cool.

**Pull request merged**
