### PR TITLE
Replaced indexOf with includes where possible

### PR DESCRIPTION
**Pull request by L2jLiga**

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
`Array.prototype.includes` was [added in ES2016](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Specifications). Correct me if I'm wrong, but I believe Terser still aims to support ES5 environments such as IE11?

Alternatively, you could change `array.indexOf(elem) >= 0` to `member(elem, array)` (from `utils.js`).

**Comment by L2jLiga** [comment]
@MattiasBuelens in master we already have some breaking changes for ES5 envs: [here](https://github.com/terser-js/terser/blob/master/lib/compress.js#L5316) and [here](https://github.com/terser-js/terser/blob/master/lib/compress.js#L5329) that were made in https://github.com/terser-js/terser/pull/255
Also in https://github.com/terser-js/terser/pull/274 I used arrow function.
Actually I don't see any reasons to write code in ES5 style to be able run Terser in IE11 when we can do it in more modern environment.

@fabiosantoscode should Terser works in ES5 environments like IE11? If yes, then we have to make little changes to be able to work

**Comment by MattiasBuelens** [comment]
Hence the "correct me if I'm wrong". I couldn't find any documentation about minimum requirements. Since #226, you need at least Node 6 to **build** Terser, but I'm not sure if that also applies to **run** Terser.

If Terser requires an ES2015 environment to run, I could change #276 to just use `Set` instead. We could even replace all `Dictionary` objects with `Map`s. 😄

**Comment by L2jLiga** [comment]
Since #226 we require node.js >= 6 to build/run Terser (both)
I'm not sure about @fabiosantoscode policies, let's wait until he's comment

**Comment by fabiosantoscode** [comment]
For terser 4.0 I'm dropping node 4 entirely, so this gets the 4.0 label.

**Comment by fabiosantoscode** [comment]
4.0 goes out this weekend, so I'm merging now after all.

**Pull request merged**
