### PR TITLE
Simplify DEFNODE constructor

### PR DESCRIPTION
**Pull request by Connormiha**
I simplified creating node construcor. I got rid of `eval` and used function declaration.

### CODE REVIEW

**Comment by L2jLiga** [comment]
I would like to rewrite whole function in ES6+ style 👍

**Comment by Connormiha** [comment]
> I would like to rewrite whole function in ES6+ style 👍

Unfortunately it is impossible at the moment. There are many prototype hacks.
It is necessary in parts gets rid of legacy inheritance.

**Comment by L2jLiga** [comment]
> Unfortunately it is impossible at the moment.

At least we can change `var` to `let`/`const` at the moment

**Comment by fabiosantoscode** [comment]
I'm not happy to merge this because the Function constructor can be optimized in a way that running a for loop on every construction can't.

`new Function(code)` is a function that gets JIT'ed.

But DEFNODE does need some simplification.

**Comment by Connormiha** [comment]
I tested it. It really slows down the performance.

**Pull request closed without merging**
